import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;
import 'package:provider/provider.dart';

// Import services and other dependencies used by the widgets
import 'services/auth_service.dart';
import 'services/hass_websocket_service.dart';
import 'services/mock_hass_websocket_service.dart';
import 'services/theme_service.dart';

// This file will be generated by widgetbook_generator
import 'widgetbook.directories.g.dart';

void main() {
  runApp(const WidgetbookApp());
}

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    final mockWs = MockHassWebSocketService();
    final themeService = ThemeService();

    // Populate with some mock data so widgets actually render
    mockWs.setMockEntity('light.rgb_lamp', {
      'entity_id': 'light.rgb_lamp',
      'state': 'on',
      'attributes': {
        'friendly_name': 'RGB Lamp',
        'brightness': 200,
        'rgb_color': [255, 0, 0],
        'supported_color_modes': ['rgb', 'brightness'],
      },
    });

    mockWs.setMockEntity('light.kitchen', {
      'entity_id': 'light.kitchen',
      'state': 'off',
      'attributes': {
        'friendly_name': 'Kitchen Light',
        'supported_color_modes': ['color_temp', 'brightness'],
        'min_mireks': 153,
        'max_mireks': 500,
      },
    });

    mockWs.setMockEntity('climate.nest', {
      'entity_id': 'climate.nest',
      'state': 'heat',
      'attributes': {
        'friendly_name': 'Living Room',
        'current_temperature': 21.5,
        'temperature': 22.0,
        'hvac_modes': ['off', 'heat', 'cool'],
        'hvac_action': 'heating',
        'preset_modes': ['home', 'away', 'eco'],
        'preset_mode': 'home',
        'fan_modes': ['on', 'auto'],
        'fan_mode': 'auto',
      },
    });

    mockWs.setMockEntity('climate.simple', {
      'entity_id': 'climate.simple',
      'state': 'off',
      'attributes': {
        'friendly_name': 'Guest Room',
        'current_temperature': 19.0,
        'temperature': 20.0,
        'hvac_modes': ['off', 'heat'],
      },
    });

    mockWs.setMockEntity('switch.coffee_maker', {
      'entity_id': 'switch.coffee_maker',
      'state': 'off',
      'attributes': {'friendly_name': 'Coffee Maker'},
    });

    mockWs.setMockEntity('binary_sensor.front_door', {
      'entity_id': 'binary_sensor.front_door',
      'state': 'off',
      'attributes': {'friendly_name': 'Front Door', 'device_class': 'door'},
    });

    mockWs.setMockEntity('sensor.room_humidity', {
      'entity_id': 'sensor.room_humidity',
      'state': '45',
      'attributes': {
        'friendly_name': 'Humidity',
        'unit_of_measurement': '%',
        'device_class': 'humidity',
      },
    });

    mockWs.setMockEntity('sensor.room_temperature', {
      'entity_id': 'sensor.room_temperature',
      'state': '22.5',
      'attributes': {
        'friendly_name': 'Temperature',
        'unit_of_measurement': '°C',
        'device_class': 'temperature',
      },
    });

    mockWs.setMockEntity('weather.home', {
      'entity_id': 'weather.home',
      'state': 'sunny',
      'attributes': {
        'friendly_name': 'Home',
        'temperature': 25,
        'humidity': 30,
        'pressure': 1013,
        'wind_speed': 10,
        'visibility': 10,
      },
    });

    mockWs.setMockEntity('media_player.living_room_tv', {
      'entity_id': 'media_player.living_room_tv',
      'state': 'playing',
      'attributes': {
        'friendly_name': 'Living Room TV',
        'media_title': 'Favorite Movie',
        'media_artist': 'Great Director',
        'supported_features': 512,
        'volume_level': 0.5,
      },
    });

    mockWs.setMockEntity('camera.front_door', {
      'entity_id': 'camera.front_door',
      'state': 'streaming',
      'attributes': {'friendly_name': 'Front Door Camera'},
    });

    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider<HassWebSocketService>.value(value: mockWs),
        ChangeNotifierProvider.value(value: themeService),
      ],
      child: Widgetbook.material(
        directories: directories,
        addons: [
          ViewportAddon([
            IosViewports.iPhone13,
            AndroidViewports.samsungGalaxyS20,
          ]),
          MaterialThemeAddon(
            themes: [
              WidgetbookTheme(
                name: 'Light',
                data: themeService.getLightTheme(),
              ),
              WidgetbookTheme(name: 'Dark', data: themeService.getDarkTheme()),
            ],
          ),
        ],
      ),
    );
  }
}
