import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;
import 'package:provider/provider.dart';

// Import services and other dependencies used by the widgets
import 'services/auth_service.dart';
import 'services/hass_websocket_service.dart';

// This file will be generated by widgetbook_generator
import 'widgetbook.directories.g.dart';

void main() {
  runApp(const WidgetbookApp());
}

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider(create: (_) => HassWebSocketService()),
      ],
      child: Widgetbook.material(
        directories: directories,
        addons: [
          MaterialThemeAddon(
            themes: [
              WidgetbookTheme(name: 'Light', data: ThemeData.light()),
              WidgetbookTheme(name: 'Dark', data: ThemeData.dark()),
            ],
          ),
          DeviceFrameAddon(
            devices: [Devices.ios.iPhone13, Devices.android.samsungGalaxyS20],
          ),
        ],
      ),
    );
  }
}
