name: hasi
base: core22
version: git
website: https://github.com/erik-seifert/hasi
source-code: https://github.com/erik-seifert/hasi
issues: https://github.com/erik-seifert/hasi/issues
summary: Home Assistant Interface - A Flutter-based Home Assistant client
description: |
  Hasi is a modern, cross-platform Home Assistant client built with Flutter.
  It provides a beautiful and intuitive interface to control your smart home
  devices, view dashboards, and interact with your Home Assistant instance.
  
  Features:
  - Connect to Home Assistant via WebSocket
  - Auto-discovery of Home Assistant instances
  - Customizable dashboards
  - Control lights, climate, sensors, cameras, and more
  - Voice control integration
  - Notifications and alerts
  - Multi-language support
  - Theme customization

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  hasi:
    command: hasi
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - unity7
      - removable-media
      - gsettings
      - pulseaudio
      - avahi-observe
    environment:
      # Flutter/GTK environment
      DISABLE_WAYLAND: '1'
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      GDK_GL: gles

parts:
  hasi:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - lld-14
      - llvm-14
      - binutils
      - libgtk-3-dev
      - libblkid-dev
      - liblzma-dev
      - libsecret-1-dev
      - libsqlite3-dev
      - libavahi-client-dev
      - libavahi-common-dev
    stage-packages:
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libpango-1.0-0
      - libcairo2
      - libsecret-1-0
      - libsqlite3-0
      - libavahi-client3
      - libavahi-common3
      - libpulse0
      - libsndfile1
      - libasound2
    override-build: |
      rm -rf build/
      craftctl default
      # Ensure the binary has the correct name
      if [ -f $CRAFT_PART_INSTALL/bin/hasi ]; then
        chmod +x $CRAFT_PART_INSTALL/bin/hasi
      fi

  # Store category: Devices and IoT
  # Desktop integration
  desktop-file:
    plugin: dump
    source: snap/gui
    organize:
      hasi.desktop: usr/share/applications/hasi.desktop
      icon.png: usr/share/icons/hicolor/512x512/apps/hasi.png

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
